version: '3.4'

services:
  sql-server-db:
    container_name: "sql-server-db"
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    ports:
      - "1433:1433"

  microservicetemplate.microservice:
    image: microservicetemplate.microservice
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
